### ISSUE TITLE
 The plugin is not loading

### ISSUE THREAD

**Issue by Harminder-Singh-Nijjar** [simonpacis/obsidian-grammarly-plugin#1]
After following the quick start guide for installing the plugin and trying to enable it, I get a popup modal in the upper right-hand side saying, "Failed to load plugin obsidian-grammarly-plugin"

The steps I followed are:
1. Download obsidian-grammarly-plugin.zip from the latest release.
2. Extract the file in a .obsidian/plugins folder in your Vault (.obsidian is probably hidden)
3. Open Obsidian, go to "Community Plugins" and enable "Grammarly Plugin".

![Obsidian_OQyc1pJyAH](https://user-images.githubusercontent.com/110620707/195911172-9a77e28b-3cee-4b15-bc99-1431754cb059.png)

**Comment by simonpacis** [comment]
Hi,

Sorry to hear you're experiencing problems with this plugin. Is your Obsidian updated to 1.0.0 and does your folder structure n your vault look like the below image?

<img width="1032" alt="Screen Shot 2022-10-14 at 5 53 37 PM" src="https://user-images.githubusercontent.com/7118482/195961804-93432248-554e-4635-bbf2-9580b73c2988.png">

If yes, then would you please provide me with all output from the Obsidian console? You can open it by pressing command+option+I (different shortcut in Windows I am sure) in Obsidian. Click on "Console" in the drawer that opens, then make sure verbose logs are on. See the image below:

<img width="783" alt="image" src="https://user-images.githubusercontent.com/7118482/195961841-b0089326-5d1f-43b2-a022-d81e3be1e907.png">

And post the output here.

All the best,
Simon

**Comment by Harminder-Singh-Nijjar** [comment]
I am currently using version 1.0.0 of Obsidian. 

Below are screenshots of my Obsidian plugins and the Grammarly plugin in File Explorer.
![explorer_n4gNOpmMez](https://user-images.githubusercontent.com/110620707/195996499-e3a9971b-1587-4553-bcfd-4666d8fea2e5.png)
![explorer_Af1g5LibAI](https://user-images.githubusercontent.com/110620707/195996526-4e969335-8d64-4b67-9f8c-b855968b25ba.png)

Here's the screenshot of my console with verbose logs on:
![Obsidian_MU2JNFvNWU](https://user-images.githubusercontent.com/110620707/195996654-a79f6e9e-ee3f-48a4-a411-b175aca71c30.png)

**Comment by Harminder-Singh-Nijjar** [comment]
After changing main.ts to main.js in the folder, I get the following output in the console:

![Obsidian_qzgJxdu25G](https://user-images.githubusercontent.com/110620707/195997783-3946d9af-3786-428d-8ba4-e6181293296d.png)

**Comment by simonpacis** [comment]
Hi Harminder,

Ah, I see what's going on. You're downloading the entire repo, not the releases.

Go to this link: https://github.com/simonpacis/obsidian-grammarly-plugin/releases/tag/0.1.1

And download the "obsidian-grammarly-plugin.zip". This is the one you need to extract.

All the best,
Simon

**Comment by Harminder-Singh-Nijjar** [comment]
I followed the directions provided above, and now the plugin is working correctly. Thank you for your quick responses, and good luck with developing this plugin!

**Comment by jjmachan** [comment]
ran into the same issue but I was someone looking to maybe contribute too and help out anyways I can so I was wondering what the dev setup was like

Also thanks for this plugin mate 😃 🙌🏽

**Comment by simonpacis** [comment]
Thanks for pointing this out. I've updated the README to be more clear on this point!
