### ISSUE TITLE
How can I help to develop the login feature?

### ISSUE THREAD

**Issue by jjanvier** [simonpacis/obsidian-grammarly-plugin#13]
I've read https://developer.grammarly.com/docs/connected-accounts#configuring-connected-accounts-for-desktop-clients-electron and I'm trying to figure out where to start to be able to code the "login" feature.

Do you have any idea @simonpacis how to start with that?

**Comment by jjanvier** [comment]
@simonpacis did you have time to take a look?

**Comment by kpgabriel** [comment]
I am trying to figure this out too. I may have a poor fundamental understanding of OAuth, but looking at the code I was trying to put something like this in the plugin.ts.

![image](https://user-images.githubusercontent.com/22206610/213777010-ea20d420-7182-4788-b543-5361c96a0bc8.png)

I am trying to figure out how to view the obsidian document. Like HTML inspection. If there is the documentation for that. I would greatly appreciate figuring out how to make the dev experience easier with obsidian. So far, you need to create an app on Grammarly's developer site. Then, from that app, make a desktop app, add a redirect URI the one they use is `example://grammarly-auth/` and then enable the connected accounts. 

[This ](https://github.com/grammarly/grammarly-for-developers/tree/main/examples/electron-javascript-npm) is an example using electron to add an account. I'm trying to relate that to this plugin.

**Comment by kpgabriel** [comment]
`ctrl+shit+i` is how we get dev tools in obsidian.

**Comment by kpgabriel** [comment]
I added this line, and it worked with the flow. But the user's Grammarly account isn't referenced. 

![image](https://user-images.githubusercontent.com/22206610/213817235-27e076a8-7e33-47fe-8456-0d1311cbc821.png)

**Comment by LaurentGla** [comment]
I issued a topic to the Grammarly support team about the need for integration with Obsidian. They have replied that they would not have a quick fix for now, so I took the liberty to make them aware of your work. They may contact you to help, hopefully.

**Comment by kpgabriel** [comment]
> 

Thanks for your support! I was able to figure it out! and made a PR.

**Comment by simonpacis** [comment]
Amazing thread, this one. Very thankful for the great work you guys are doing. Unfortunately I'm totally slammed with work and studies at the moment, so haven't been able to dedicate any time to this project. PR merged, I'll zip it up and create a new version later tonight (I'm GMT+8).

**Comment by LaurentGla** [comment]
Thanks so much for the update. Let us know when the new version is on. Would mind adding instructions for those, like me, who have installed the previous one?  I suppose we would need to overwrite it, but I'd like to make sure we do it the right way.
I suppose you will also ensure the new plugin is referenced in the community plugins?

**Comment by simonpacis** [comment]
@LaurentGla the release is here: https://github.com/simonpacis/obsidian-grammarly-plugin/releases/tag/0.2.2

1. Delete the directory ".obsidian/plugins/obsidian-grammarly-plugin" at the root of your Obsidian vault.
2. Download the .zip-file and extract it in your .obsidian/plugins folder so that you get the directory ".obsidian/plugins/obsidian-grammarly-plugin" again.
3. Launch Obsidian. You might have to enable the plugin in settings again.

**Comment by LaurentGla** [comment]
Aha... for some reason,  it is not functional anymore although I have followed your instructions. 
Is it normal that it is still version 0.1.1. on the plugin list?

**Comment by kpgabriel** [comment]
The Grammarly app client ID will need connected accounts enabled and you
will need to make a Desktop client ID and add obsidian://grammarly-auth to
the URLs for your Grammarly app.

**Comment by kpgabriel** [comment]
This can be done through the portal for developer.grammarly.com.

**Comment by kpgabriel** [comment]
It will look something like this in the portal 

![Screenshot_20230123-141808](https://user-images.githubusercontent.com/22206610/214129962-386cda89-5760-454b-8abf-afa9b2a6b945.png)

![Screenshot_20230123-141800](https://user-images.githubusercontent.com/22206610/214130004-edf3de7f-d2a8-4ccc-8262-a4fd88389151.png)


You can use my client ID as well. I have it already set up.
`client_CKjJiRL3gDiX5Jsfa2Q8hj`

I just removed it from the code because it was hard coded.

**Comment by LaurentGla** [comment]
I could manage by using your client ID. I could not make the other option work (it asked for URLs that I don't have). Thanks a lot!

**Comment by simonpacis** [comment]
> Is it normal that it is still version 0.1.1. on the plugin list?

This is a mistake. If you download version 0.2.2 again it should be fixed.

**Comment by jjanvier** [comment]
Thank you @kpgabriel and @simonpacis. It works perfectly :pray:

**Comment by simonpacis** [comment]
Thank you @jjanvier, but all thanks to @kpgabriel!

I've added a client id to version 0.2.2 which enables logging in without having to setup your own client id.
