### ISSUE TITLE
Unable to use own Grammarly ID

### ISSUE THREAD

**Issue by Jetpackjules11** [simonpacis/obsidian-grammarly-plugin#15]
Tried getting my own, but when I paste it and restart obsidian the plugin says "Starting Grammarly..." but then nothing happens. Works fine when I use the supplied ID, though.

**Comment by Ruminov** [comment]
I had this same problem before, there are two different client IDs one for the Web and one for the Desktop, I was originally using  the Web Client ID, so using the Desktop Client ID fixed this problem for me.

**Comment by Jetpackjules** [comment]
Thanks! And how do I acess the app ID?

**Comment by Ruminov** [comment]
I followed this process:
[How to get client ID](https://support.grammarly.com/hc/en-us/articles/4409115170701-Where-can-I-get-a-Client-ID-#:~:text=To%20obtain%20a%20Client%20ID,its%20name%2C%20and%20click%20Create.)

When you finish, make sure to use the client ID from the "Desktop" tab.

**Comment by Jetpackjules** [comment]
Where did you see the "Desktop" tab? (I can only see web..)

<img width="228" alt="image" src="https://user-images.githubusercontent.com/46934175/211361794-3c99fd44-960e-4ef1-ad69-951d16f788fc.png">

**Comment by Ruminov** [comment]
I'm not sure why "Desktop" it's not available to you, that option should be there from the beginning.

![image](https://user-images.githubusercontent.com/74424348/211673971-ff94a527-a1bf-4d23-9f9a-ef7863bc8c6d.png)

**Comment by simonpacis** [comment]
Version 0.2.2 has an updated client ID supplied.
