### ISSUE TITLE
Obsidian 1.1.9, Grammarly plugin 0.2.2 failed to load

### ISSUE THREAD

**Issue by victorkr** [simonpacis/obsidian-grammarly-plugin#17]
I am trying to install the obsidian-grammarly-plugin 0.2.2 in Obsidian 1.1.9, following this instruction https://github.com/simonpacis/obsidian-grammarly-plugin#installation. I can't enable the plugin, the error "Failed to load plugin obsidian-grammaly-plugin". Could you please suggest what I am doing wrong?

**Comment by victorkr** [comment]
It was my misunderstanding.

**Comment by hidegh** [comment]
@victorkr how did you solve the problem? I got the same error message when I try to enable the plugin.

**Comment by simonpacis** [comment]
@hidegh, I'm willing to bet you're downloading the entire repo as a .zip. This is not the correct way to install the plugin. Make sure you download the zip from the releases-page. I'm pasting from the instructions in README.md:

- Download obsidian-grammarly-plugin.zip from the latest release.
	- Go to: https://github.com/simonpacis/obsidian-grammarly-plugin/releases
	- Go to the latest release, click "Assets" and download the zip-file from here.
- Extract the file in a .obsidian/plugins folder in your Vault (.obsidian is probably hidden)
- Open Obsidian, go to "Community Plugins" and enable "Grammarly Plugin".

Hope that clears it up!

**Comment by hidegh** [comment]
@simonpacis @victorkr be aware that the [1.0.0](https://github.com/simonpacis/obsidian-grammarly-plugin/releases/tag/1.0.0) version does not have the separate `obsidian-grammarly-plugin.zip` in the assets!
