### ISSUE TITLE
Fail to load plugin obsidian-grammarly-plugin

### ISSUE THREAD

**Issue by khangdx1998** [simonpacis/obsidian-grammarly-plugin#18]
I just downloaded the latest release. I encountered the message "Fail to load plugin obsidian-grammaryly-plugin" as I clicked on **Community Plugins"

**Comment by simonpacis** [comment]
Hi,

There was an error with v 1.0.0. Please download the latest version (which is now 0.2.2) and it should work.

**Comment by Jzheng213** [comment]
I am running into the same error with 0.22.

**Comment by cristianmtr** [comment]
I am also running into this error @simonpacis

**Comment by simonpacis** [comment]
Taking a look at it now @cristianmtr.

**Comment by simonpacis** [comment]
Downloading the .zip from the assets of release 0.2.2 on a new Obsidian vault causes no issues here. Unfortunately, if it persists, I will need more info to debug the problem.

Please ensure that you are downloading and installing the following zip: https://github.com/simonpacis/obsidian-grammarly-plugin/releases/download/0.2.2/obsidian-grammarly-plugin.zip

**Comment by Jzheng213** [comment]
Oh looks like it works. I probably missed something in the setup.

Thank you so much.

**Comment by simonpacis** [comment]
Awesome, glad to hear it!

**Comment by cristianmtr** [comment]
Hey. It still doesn't work for me. Is there a way to see the logs?

**Comment by cristianmtr** [comment]
Ah figured it out. I downloaded the full source code, not the zip. Now it works. Thanks!
