### ISSUE TITLE
BRAT Compability

### ISSUE THREAD

**Issue by ericrallen** [simonpacis/obsidian-grammarly-plugin#19]
I'm super excited to see Grammarly start to work in Obsidian.

The [Beta Reviewer's Auto-Update Tool (BRAT)](https://github.com/TfTHacker/obsidian42-brat) is a great way for folks to test out extensions that are under development and haven't been submitted to the Community Plugins registry yet while still keeping them up to date without needing to download and unzip the plugin every update manually.

I think the only thing this project needs to get this working is to keep the `manifest.json` `version` number up to date with the current Release version in GitHub to [resolve the `"main.js not found in the Release"` error](https://github.com/TfTHacker/obsidian42-brat/issues/51).

As a side note, I've also been developing a plugin and ended up combining GitHub Actions, [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/), [semantic-release](https://github.com/semantic-release/semantic-release), and the [version-bump script](https://github.com/simonpacis/obsidian-grammarly-plugin/blob/master/version-bump.mjs) to keep my manifest version up to date automatically. If you're interested, I'd be happy to help set up a similar [release](https://github.com/InterwebAlchemy/obsidian-ai-research-assistant/releases) [workflow](https://github.com/InterwebAlchemy/obsidian-ai-research-assistant/blob/main/.github/workflows/release.yml) for this plugin, but I also understand that it's a bit of extra overhead you may not want.

**Comment by ericrallen** [comment]
I just noticed that you're getting it ready for a 1.0.0 and submission to the official plugin registry.

I'm going to close this one for now and might revisit it and add a PR for including the [`manifest-beta.json`](https://github.com/TfTHacker/obsidian42-brat/blob/main/help/developers.md#manifest-betajson) that BRAT can use to allow testers to keep up to date with pre-releases after a plugin has been officially released.

**Comment by simonpacis** [comment]
Still working out some kinks for 1.0.0. Added BRAT to the readme. Thank you, I was unaware of it!
