### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by phamleduy04** [simonpacis/obsidian-grammarly-plugin#23]
![image](https://user-images.githubusercontent.com/32657584/231906865-9edcd794-693d-4bfc-870b-e7cbebf2922c.png)

Resposne get from grammarly api
```json
{"message":"validation error","errors":["response_type must not be null"]}
```

**Comment by simonpacis** [comment]
Hi,

Is this still an issue?

Simon

**Comment by phamleduy04** [comment]
Hi,

I tried again at a later time and it works now. Thank you for your update
