### ISSUE TITLE
Latex in note causes editor SDK error

### ISSUE THREAD

**Issue by SenorMonito** [simonpacis/obsidian-grammarly-plugin#24]
Thank you guys for developing this plugin. Grammarly is a very useful tool and seeing it integrated into Obsidian would be amazing.

I have been testing the [0.2.3](https://github.com/simonpacis/obsidian-grammarly-plugin/releases/tag/0.2.3) release of the plugin on Mac M1 with MacOS 13.3.1 and noticed that latex formulas in a note cause an unhandled error.

For example, this test text:

> Some text from a Grammarly example document: "Mispellings and grammatical errors can effect your credibility. The same goes for misused commas, and other types of punctuation . Not only will Grammarly underline these issues in red, it will also showed you how to correctly write the sentence."

works as expected. It will highlight mistakes and offer suggestions.

But the same text with a latex expression added:

> Some text from a Grammarly example document: "Mispellings and grammatical errors can effect your credibility. The same goes for misused commas, and other types of punctuation . Not only will Grammarly underline these issues in red, it will also showed you how to correctly write the sentence." There exist $𝑥,𝑦 \in \mathbb{Z}$ so that: $𝑎𝑥+𝑏𝑦=gcd(𝑎,𝑏)$

gives this error in the developer console:

```
Uncaught TypeError: Cannot read
https://js.grammarly.com/grammarly-editor-sdk@2.3?clientId=client_DNSZ5n1LBKo8CDovJJ85DT&packageName=%40grammarly%2Feditor-sdk
properties of undefined (reading 'grammarlySkip')
```

I hope this helps. If you need any further information please let me know. 
Thank you again for the fantastic work.

**Comment by simonpacis** [comment]
Hi SenorMonito,

Thank you for the report, I will take a look at it. However, I do not think I will be able to solve it. PRs are always welcome.

All the best,
Simon
