### ISSUE TITLE
Corrections are sometimes not applied.

### ISSUE THREAD

**Issue by lazakoa** [simonpacis/obsidian-grammarly-plugin#25]
Everything was working fine for months unitl about two weeks ago when corrections sometimes stopped applying. I click on the suggestion to apply it, and nothing happens. Sometimes it works in one part of the document, and then fails while trying to edit other parts of the document.

**Comment by simonpacis** [comment]
Hi,

Do you use the vim-plugin? I've notice that I need to be in insert mode for it to apply suggestions.

Simon

**Comment by lazakoa** [comment]
I do use the vim plugin, and I noticed the same behavior too when testing it just now. I think this is resolved.

**Comment by simonpacis** [comment]
Yeh, it's very annoying! It is probably outside of the scope of this plugin to fix it, but if I stumble upon a solution I will make sure to update this issue :)
