### ISSUE TITLE
Enhancement: change hotkey

### ISSUE THREAD

**Issue by ms3056** [simonpacis/obsidian-grammarly-plugin#26]
Hi - I would like the option to change the hotkey. ctrl+alt+g does something different on my Windows setup. 

Thank - btw - SO MUCH - for this plugin!

**Comment by simonpacis** [comment]
Hi,

I'm glad you enjoy the plug-in, thank you! Unfortunately this hotkey is set by Grammarly and not the plug-in:

"You can enter keyboard mode with the following commands, depending on your operating system.

Mac: Cmd+Ctrl+G
Windows: Ctrl+Alt+G
When you're ready to leave keyboard mode, press the escape key."

[https://developer.grammarly.com/docs/grammarly-ux)(https://developer.grammarly.com/docs/grammarly-ux)

As such, this will be marked wontfix.

Thank you!

Simon
