### ISSUE TITLE
Bug: Accepting a Suggestion does not work in vim-normal mode

### ISSUE THREAD

**Issue by chrisgrieser** [simonpacis/obsidian-grammarly-plugin#29]
Pressing the `Accept` button does not work you have Obsidian's vim mode enabled and are in normal mode. In insert mode, it works fine.

I know from a different plugin that the following snippet can be used to programmatically enter insert mode and should be added before the suggestion is implemented:

```ts
// enter insert mode for vim users
if (app.vault.getConfig("vimMode")) {
   const cm = active_view.editor.cm.cm
   window.CodeMirrorAdapter.Vim.handleKey(cm, "i", "mapping")
}
```
I'd make a PR, but I am not sure where exactly the snippet would have to be inserted.

**Comment by simonpacis** [comment]
Hi Chris,

Thanks for the snippet! Unfortunately for this plugin, it is the Grammarly SDK which handles the actual word substitution. As such, there is no straightforward way to implement automatically entering insert mode when substituting words.

I'll look into it, but I am not sure if I'll be able to solve it.

Simon

**Comment by simonpacis** [comment]
Unfortunately not, this is also handled by the SDK.

**Comment by chrisgrieser** [comment]
too bad 😕 

anyhow, thanks for the plugin and the quick (partial) fix though!
