### ISSUE TITLE
Grammerly button disappears if you close a tab

### ISSUE THREAD

**Issue by patleeman** [simonpacis/obsidian-grammarly-plugin#3]
Obsidian v1.0.0

Repro steps:

- Enable the plugin, Grammerly button should show up in the bottom left.
- Close a tab
- Open a new document
- Grammerly button doesn't show up.

**Comment by patleeman** [comment]
It looks like re-enabling the plugin will re-add the button. Probably not a bug so much as mis-matched expectations on my end!

**Comment by simonpacis** [comment]
Hi,

Yeah, right now it loads the JavaScript Grammarly Editor SDK into the currently active view. Hopefully, down the line, we'll be able to integrate it in a better (or automated) fashion.

Best,
Simon
