### ISSUE TITLE
Incorrect placement of Grammarly popover

### ISSUE THREAD

**Issue by SebbeJohansson** [simonpacis/obsidian-grammarly-plugin#4]
Hi! For me the error window is always being displayed further to the right compared to where the error actually is in the text.

Example:
![image](https://user-images.githubusercontent.com/5083273/198901370-8da835c6-451a-496e-b200-9d0fb52e4a79.png)

I am running Obsidian 1.0.3.

**Comment by simonpacis** [comment]
Hi,

Thank you for this bug report. It is a known issue that will be addressed in the next update. You will be able to set an offset for the Grammarly popover, as different Obsidian themes unfortunately affect the position of the Grammarly popover.

Look forward to this update on the next couple of days (might be a little more, busy at the moment).

All the best,
Simon Pacis

**Comment by SebbeJohansson** [comment]
@simonpacis Thanks for checking and letting me know.
If I have the time I might look into helping with development in some way!

**Comment by bobhenkel** [comment]
Is there any way for that popover to be a movable thing with the mouse?  An offset is a great start and may be good enough. I just thought I would ask while this issue is still active. 

Great plugin, by the way. I love it!

Much appreciate your efforts!
Bob

**Comment by SebbeJohansson** [comment]
@bobhenkel In what situation do you keep the popup long enough that having it moveable is worth it? The only time I use the popup is when I'm holding over/clicked on an incorrect word. I cant see a situation where I would need to move it.

**Comment by simonpacis** [comment]
Hi all,

I agree that at the moment it doesn't seem necessary to develop this functionality.

However, if you disagree, I wouldn't mind hearing the use case where you believe a draggable popover would be useful.

All the best,
Simon

**Comment by simonpacis** [comment]
This issue has now been resolved and is included in version 0.2.0
