### ISSUE TITLE
Submit to Community Repo

### ISSUE THREAD

**Issue by bobhenkel** [simonpacis/obsidian-grammarly-plugin#5]
Nice work looks great. It would be nice to get it added so someone can install it via the Obsidian settings panel.

**Comment by simonpacis** [comment]
Hi Bob,

Thank you for this suggestion! The plan is definitely to submit the plug-in to the Community Repo, but I would like to be a little bit further along with some of the planned features before doing so. Most importantly the inclusion of a settings panel and some more testing.

I will update this issue when the plug-in is submitted to the Community Repo.

All the best,
Simon Pacis

**Comment by nicolamassarenti** [comment]
Hi @simonpacis, 

Are there any updates on this issue?

**Comment by simonpacis** [comment]
This is in the works, there are some quality checks that need to be accomplished before. ETA ~2-3 weeks.
