### ISSUE TITLE
Update README.md for TS compilation

### ISSUE THREAD

**Issue by sebapoole** [simonpacis/obsidian-grammarly-plugin#6]
Add steps to the readme for compilation from TS to JS:

```
## Installation

A quick starting guide for installing the plugin:

-   Download obsidian-grammarly-plugin.zip from the latest release.
    -   Go to: https://github.com/simonpacis/obsidian-grammarly-plugin/releases.
    -   Go to the latest release, click "Assets" and download the zip file from here.
-   Extract the file in a .obsidian/plugins folder in your Vault (.obsidian is probably hidden).
-   Run `npm i` to install dependencies.
-   Run `npm run build` to compile the plugin.
-   Open Obsidian, go to "Community Plugins" and enable "Grammarly Plugin".
```

**Comment by simonpacis** [comment]
Hi Seb,

Sure, I'll add it! For now, it's just the directions from here: https://marcus.se.net/obsidian-plugin-docs/getting-started/create-your-first-plugin

All the best,
Simon Pacis

**Comment by simonpacis** [comment]
Hi,

Thank you for this suggestion.

It would, however, be better to have separate steps for using and developing the plug-in.

There is no need to clone the repo to simply use the plug-in. The latest version of the plug-in is always available under "Releases", and the .zip-file from there is what should be installed.

The only reason you'd need to compile it would be if you're working on the plug-in.

Thank you, I'll update the readme.

Best,
Simon
