### ISSUE TITLE
Why hide/move "Grammarly-powered editor" tooltip?

### ISSUE THREAD

**Issue by znck** [simonpacis/obsidian-grammarly-plugin#7]
We use aria-label for screen readers to convey that user is in an Grammarly-powered editor. If it's causing any issue, please create an issue in the http://github.com/grammarly/grammarly-for-developers repository.

**Comment by simonpacis** [comment]
Hi Rahul,

Maybe I should add a setting so people can choose whether they want it; accessibility is important.

The primary reason for removing it was simply that it was in the way. It would show up at the bottom of the Obsidian editor in a way that made using Grammarly in Obsidian look and feel hacky, so to speak.

I'll see if I can post a screenshot of it later.

Best,
Simon

**Comment by znck** [comment]
Can you share a screenshot? I'll try to fix it in the SDK.

**Comment by simonpacis** [comment]
![Screen Recording 2022-11-11 at 1 42 13 PM](https://user-images.githubusercontent.com/7118482/201343044-a4c68488-5bf5-4a32-8556-81f0e9383e24.gif)

Check out this GIF. Every time the mouse hovers on the editor the tooltip shows up at the bottom. Personally I find it rather annoying when I'm trying to write alongside using Grammarly.

Best,
Simon

**Comment by znck** [comment]
Will fix it.

**Comment by simonpacis** [comment]
Thank you @znck! Will this be pushed in a future version of the SDK or is it already out?

**Comment by znck** [comment]
Will be in future version. I'll let you know when done.

**Comment by simonpacis** [comment]
Perfect, thank you.
