### ISSUE TITLE
The pop-up disappears too quickly

### ISSUE THREAD

**Issue by moriakaice** [simonpacis/obsidian-grammarly-plugin#8]
Sometimes, when the pop-up appears far from the text to be corrected, it can disappear before the pointer can get there. This happens, for example, in the `Obsidian Nord` theme.

A solution could be having a setting to make the pop-up permanent until closed by clicking or by approving/declining the suggestion.

**Comment by simonpacis** [comment]
Hi @moriakaice,

Unfortunately the popup is controlled by the Grammarly Editor SDK which I do not develop. I'll see what I can do.

Best,
Simon
