### ISSUE TITLE
Suggestions as a beta user

### ISSUE THREAD

**Issue by yiwkd2** [simonpacis/obsidian-grammarly-plugin#9]
Hi,

First of all, thank you guys for developing this plugin.

I have some suggestions for a better experience.

1. It would be nice if we can enable Grammarly permanently in the settings.
2. It would be nice if we have a choice of the location of the Grammarly button. Currently, it's on the left, but I'm used to seeing it on the right, and there may be more people like me.

Best,
Youngin Kim

**Comment by 0xFlo** [comment]
I can't wait for the account login to unlock all features 🌊

**Comment by simonpacis** [comment]
Thank you @yiwkd2! These are good suggestions.

And @0xFlo, hopefully we'll be able to get this feature down soon.

Best,
Simon
